version: '3'
services:
  server:
    image: albaitas/react-mongodb-express-server:latest
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - client

  client:
    image: albaitas/react-mongodb-express-client:latest
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:5000
